### ISSUE TITLE
Kanban task Items assignment

### ISSUE THREAD

**Issue by emmanuelsteven** [emmanuelsteven/spaceMission#99]
- There are basically two people working on this project.
- The task Items have been assigned  equally among us 
- https://github.com/emmanuelsteven/spaceMission/issues

**Comment by t-yanick** [comment]
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @emmanuelsteven and @BezzB , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Cards distributed in a fairway
:heavy_check_mark: All required card categories present
:heavy_check_mark:  Averagely same number of points per team member
:heavy_check_mark: Project requirements well respected

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
